name: Check New Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    environment: build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #  Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Run tests
        run: mvn -B clean install
